abhijeet007rocks8/Dev-Scripts

- README.md
> Added Contributors List

- Go/Crypto-Scraper/README.md
- Go/Crypto-Scraper/main.go
- #55 
- A webscraper written in golang, it can scrape prices of the top crypto currencies.
> Crypto Scraper

- JAVA/Ping pong/Ball.java
- JAVA/Ping pong/GameFrame.java
- JAVA/Ping pong/GamePanel.java
- JAVA/Ping pong/Paddle.java
- JAVA/Ping pong/PongGame.java
- JAVA/Ping pong/README.md
- JAVA/Ping pong/Score.java
PR for the issue #82 
It is an endless 2 player ping pong game made using Java.
> PR to add a Ping pong game made in Java

- Python/Week Day Calculator/DayExtractor.py
- Python/Week Day Calculator/README.md
Issue Resolved : https://github.com/abhijeet007rocks8/Dev-Scripts/issues/42
Added python code to calculate weekday from date passed as an argument in DD/MM/YYYY format.
> Week day calculator - script added

- Web Development/Customer_Review_Webapp/app.py
- Web Development/Customer_Review_Webapp/readme.md
- Web Development/Customer_Review_Webapp/reviews.csv
- Web Development/Customer_Review_Webapp/templates/index.html
| Fixes       | #128  |
Added A Flask based app that provides the user with a form to fill a feedback about a product and saves it into a csv file to be listed in a simple webpage
* Install the required dependencies
```bash
pip3 install flask wtforms pandas
```
* Run the app
```bash
python3 app.py
```
* App usage is accompanied in the demonstration video
https://user-images.githubusercontent.com/64689436/157647479-742d1948-0a06-45a1-918c-313bc04334d8.mp4
fixes #128 
PR made under GSSoC'22 contribution
> Added Customer_Review_Webapp files

- Web Development/Qoutes_Generator/index.html
- Web Development/Qoutes_Generator/readme.md
- Web Development/Qoutes_Generator/script.js
- Web Development/Qoutes_Generator/style.css
| Fixes       | # Issue No. |
Added Quote Generator.... --> html,css,js..
code in html,css,js..
- [ yes] New project (non-breaking change which adds functionality)
- [yes ] My code follows the style guidelines of this project
- [ yes] I have performed a self-review of my own code
- [ yes] I have commented my code, particularly in hard-to-understand areas
- [yes ] I have included a README.md file
- [yes ] My project follows this structure: Domain Folder/ Project Name Folder/ Project files and Readme.md files
- [ yes] I am a GSSoC'22 Participant
screenshot --> 
video uploded :
https://user-images.githubusercontent.com/78314622/158870938-9751970d-b3de-418f-93ce-909fee924017.mp4
https://user-images.githubusercontent.com/78314622/158871353-aa9640df-2a5b-49e9-aa …
> Quotes Generetor done

- Python/Machine Learning/Disease_Predictor/README.md
| Fixes       | # Issue No. |
| Typing mistake s      |    #179    |
> Fixed typos in readme

- Web Development/Spock_Rock_Game/confetti.js
- Web Development/Spock_Rock_Game/index.html
- Web Development/Spock_Rock_Game/readme.md
- Web Development/Spock_Rock_Game/script.js
- Web Development/Spock_Rock_Game/style.css
| Spock_ROck_Game added      | #164 |
It is a Game like Rock paper seissor ......
Scissors cuts paper, paper covers rock, rock crushes lizard, lizard poisons Spock, Spock smashes scissors, scissors decapitates lizard, lizard eats paper, paper disproves Spock, Spock vaporizes rock, and as it always has, rock crushes scissors.
Kind of game u can enjoy in free time..... UI is simple u can play Easily .....
languages include :-
Html
Css
js
- [yes ] New project (non-breaking change which adds functionality)
played  by mee...
- [yes ] My code follows the style guidelines of this project
- [ yes] I have performed a self-review of my own code
- [yes ] I have commented my code, particularly in hard-to-understand areas
- [ yes] I have included a README.md file
- [ …
> Game added

- Python/Snake_Water_Gun/README.md
- Python/Snake_Water_Gun/Snake_Water_Gun.py
| Added Snake Water and Gun Game in python                     | #155 |
| :-------:       |    :-----:   |    
I have added Snake, water, and gun game in python. This is very interesting game which we can play on the computer.
This program is run by me using python with famous IDE Visual Studio Code.
> Added Snake water and gun game in python

- .github/ISSUE_TEMPLATE/create-an-issue.yaml
- .github/ISSUE_TEMPLATE/issue-template.yaml
- .github/pull_request_template.md
| Fixes       | #344  |
Revised template to include C under dropdown list for Tech Stack. 
No Test Required.
> Revised templates to add Scripts/Projects in C

- Python/Image_Object_Detector/readme.md
- Python/Image_Object_Detector/script.py
| Fixes       | #296  |
Added a python script used to detect an object from an image by providing it a template image of that object.
https://user-images.githubusercontent.com/64689436/162295049-e650f607-a56b-4d0a-95d4-2a2110e74c9f.mp4
closes #296
> Added image object detector files

- Python/LinkedIn_Connections_Scraper/readme.md
- Python/LinkedIn_Connections_Scraper/script.py
| Fixes       | #240  |
A Python script that scraps linkedin connections and dump the extracted data into a CSV file.
Unfortunately I can't add a demonstration video on this as there are many personal information to expose for such a project including account credentials. but I did explain how to run the project in the readme. and here is a portion of my scrapped connections in the csv file
https://user-images.githubusercontent.com/64689436/162078666-919588b7-ff2d-46e0-9186-aeff9bfc0d41.mp4
fixes #240
> Added LinkedIn Connections Scraper files

- Web Development/Number_of_Days_Calculator/Readme.md
- Web Development/Number_of_Days_Calculator/app.js
- Web Development/Number_of_Days_Calculator/index.html
- Web Development/Number_of_Days_Calculator/style.css
| Fixes       | #347 |
This calculator helps to calculate number of days between two specified dates.
This has been tested on local pc and local browser with a demonstrating video in readme.md file.
> Adding Number of Days Calc

- Python/GitHub_Profile_Scraper/readme.md
- Python/GitHub_Profile_Scraper/script.py
| Fixes       | #378  |
Added a Python Script that scraps a GitHub profile by providing a username, and saves the data into a .md file.
https://user-images.githubusercontent.com/64689436/163694620-3eb7b64e-0231-4a6e-a962-51f3491b1656.mp4
Python
fixes #378 
PR made under GSSoC'22 contributions.
> Added Github_Profile_Scraper files

- README.md
| Fixes       | # Issue No. | #391 
> Adding Project Mentors Section, GSSoC link, Project Admin name and improving README.md style

- NodeJS/SQLite3_DB_CRUD/MPanel.js
- NodeJS/SQLite3_DB_CRUD/package-lock.json
- NodeJS/SQLite3_DB_CRUD/package.json
- NodeJS/SQLite3_DB_CRUD/readme.md
| Fixes       | #379  |
Add a NodeJS app that implelements basic CRUD operations on a SQLite3 DB with some additional features such as:
- Printing Existing Tables
- Switch Between Tables
- Read, Update, Delete: Tables and Records
https://user-images.githubusercontent.com/64689436/164506870-300e41d0-da3c-47b7-8d19-bddfdeae457b.mp4
NodeJS
fixes #379
> Added SQL CRUD using NodeJS files

- Web Development/Word_Definition/Readme.md
- Web Development/Word_Definition/css/style.css
- Web Development/Word_Definition/index.html
- Web Development/Word_Definition/script/app.js
> added Word_definition project in the Web Development

- Web Development/Calculate BMI/index.html
- Web Development/Calculate BMI/readme.md
- Web Development/Calculate BMI/script.js
- Web Development/Calculate BMI/style.css
| Fixes       | #393 |
> _It's a simple website build using HTML, CSS & JavaScript.
It will take two inputs from the user, height (in cms) and weight (in kg), and based on the input values BMI will be calculated and 
It has 4 categories:
- BMI >= 30  -> <b> Obesity  </b>
- BMI = (25 to 29.9)  -> <b> Overweight </b>
- BMI = (18.5 to 24.9)  -><b> Normal </b>
- BMI < 18.5  -> <b> Underweight </b>
- Tested on Github Pages and on own Local Machine
- HTML,CSS,JS
https://user-images.githubusercontent.com/77873383/164958677-5ce7941f-0223-4331-99ce-68030ff600ab.mp4
> Calculate BMI💪

- Python/Youtube_Stats_Scraper/readme.md
- Python/Youtube_Stats_Scraper/script.py
| Fixes       | #413  |
Added a Python script that scraps a provided youtube link and prints out it stats:
* Title Name
* Views number
* Channel Name
* Subscriber Number
* Likes Number
https://user-images.githubusercontent.com/64689436/164945586-d0232636-5329-4ce5-ab20-c3dc78d8e53e.mp4
Python -> selenium4
fixes #413
> Added Youtube_Vid_Stats_Scrapper files

- C/README.md
- C/UDP Echo Client-Server Program/README.md
- C/UDP Echo Client-Server Program/client.c
- C/UDP Echo Client-Server Program/server.c
| Fixes       | #452  |
I have added a UDP Client-Server Echo program using C and linux.
tested in Linux terminal
C,Linux
> UDP Echo Client Server Program

- Python/LinkedIn_Video_Downloader/readme.md
- Python/LinkedIn_Video_Downloader/script.py
| Fixes       | #427  |
Added a Python script that downloads a provided LinkedIn video URL.
fixes #427 
https://user-images.githubusercontent.com/64689436/166953645-6b1e95da-78a5-4dad-9e27-c71de739cfe2.mp4
Python
> Added LinkedIn_Video_Downloader files

- NodeJS/NodeJS_auth/.env
- NodeJS/NodeJS_auth/app.js
- NodeJS/NodeJS_auth/package-lock.json
- NodeJS/NodeJS_auth/package.json
- NodeJS/NodeJS_auth/passport-config.js
- NodeJS/NodeJS_auth/readme.md
- NodeJS/NodeJS_auth/views/index.ejs
- NodeJS/NodeJS_auth/views/login.ejs
- NodeJS/NodeJS_auth/views/register.ejs
| Fixes       | #455  |
Added NodeJS web app that implements basic authentication system.
https://user-images.githubusercontent.com/64689436/166973523-53210102-ed3b-4be7-8583-c5ffe44eec41.mp4
Nodejs
fixes #455
> Added NodeJS_auth files

- Python/Youtube-video-downloader/.idea/.gitignore
- Python/Youtube-video-downloader/.idea/inspectionProfiles/Project_Default.xml
- Python/Youtube-video-downloader/.idea/inspectionProfiles/profiles_settings.xml
- Python/Youtube-video-downloader/.idea/misc.xml
- Python/Youtube-video-downloader/.idea/modules.xml
- Python/Youtube-video-downloader/.idea/yt do.iml
- Python/Youtube-video-downloader/README.md
- Python/Youtube-video-downloader/main.py
| Fixes       | #476  |
I hv provided video.
> Youtube-video-downloader

- NodeJS/URL_Shortner/package-lock.json
- NodeJS/URL_Shortner/package.json
- NodeJS/URL_Shortner/readme.md
- NodeJS/URL_Shortner/server.js
- NodeJS/URL_Shortner/views/home.ejs
| Fixes       | #507  |
Added a URL shortner app using NodeJS.
closes #507 
https://user-images.githubusercontent.com/64689436/168578121-050f0bca-7eaf-478a-83c1-1f2f632e4443.mp4
NodeJS
> Added URL_Shortner NodeJS App

- Web Development/Speed_Typing_Game/game.js
- Web Development/Speed_Typing_Game/index.html
- Web Development/Speed_Typing_Game/readme.md
- Web Development/Speed_Typing_Game/styles.css
| Fixes       | #508  |
Added a speed typing game which calculates the required time to type in a sentence.
closes #508 
https://user-images.githubusercontent.com/64689436/168603578-10b9c570-d7b1-44f2-ba3a-81c723fb90d4.mp4
Web Development
* HTMl
* CSS
* JS
*
> Added Speed_Typing_Game files

- Web Development/irctc/index.html
- Web Development/irctc/readme.md
- Web Development/irctc/script.js
- Web Development/irctc/style.css
| Fixes       | # Issue No. |
| #370      |    #370   |    
IRCTC landing page
Html
CSS
Javascript
> Irctc landing page done

- NodeJS/Chat_Rooms/package-lock.json
- NodeJS/Chat_Rooms/package.json
- NodeJS/Chat_Rooms/public/script.js
- NodeJS/Chat_Rooms/readme.md
- NodeJS/Chat_Rooms/server.js
- NodeJS/Chat_Rooms/views/index.ejs
- NodeJS/Chat_Rooms/views/room.ejs
| Fixes       | #548  |
Add a NodeJS app that features making chat rooms and send real time messages between users.
fixes #548 
https://user-images.githubusercontent.com/64689436/169326076-d5d469c4-f181-43f1-b240-bbf8572c4409.mp4
NodeJS
> Added NodeJS_Chat_Rooms files

- Web Development/Drawing_Space/Readme.md
- Web Development/Drawing_Space/index.html
- Web Development/Drawing_Space/script.js
- Web Development/Drawing_Space/style.css
| Fixes       | #587 |
A well-designed, sufficient Drawing Space which is very useful for the kids.
* Users can increase or decrease the size of the pen.
* Change the color of the pen according to them.
* Clear the drawing Area by clicking the X button provided.
> Adding a Drawing Space

- Web Development/Hoverboard/Readme.md
- Web Development/Hoverboard/index.html
- Web Development/Hoverboard/script.js
- Web Development/Hoverboard/style.css
| Fixes       | #586 |
A Project names Hoverboard which is an interesting one to play with.
* We can hover to the boxes made and see the different patterns and changing color patterns.
This has been tested on my local browser.
> Adding Project Hoverboard

- Web Development/Countdown_Animation/Readme.md
- Web Development/Countdown_Animation/app.js
- Web Development/Countdown_Animation/index.html
- Web Development/Countdown_Animation/style.css
| Fixes       | #516 |
I have added a simple and designed Project of Countdown Animation.
This has been tested in my local PC in local browser.
> Adding Countdown Animation

- C/UDP Time Client-Server Program/README.md
- C/UDP Time Client-Server Program/client.c
- C/UDP Time Client-Server Program/server.c
| Fixes       | #461 |
I have shown the client-server architecture using the UDP protocol.There is a server.c and a client.c. The client will then try to bind with the server.The remote server will send the time(as per server) to the client, which the client will then display.
It is an implementation of client-server connection and communication using UDP to show how to retrieve the time of a remote server.
using C,Linux
C
> UDP Time Program

- Web Development/3D_Sapes_Volume_Calculator/Readme.md
- Web Development/3D_Sapes_Volume_Calculator/index.html
- Web Development/3D_Sapes_Volume_Calculator/script.js
- Web Development/3D_Sapes_Volume_Calculator/style.css
| Fixes       | #603 |
This calculator helps to calculate the volume of different 3D Shapes.
This has been tested on my local browser.
> Adding 3D Shapes Volume Calculator

- Web Development/Movie_App/Readme.md
- Web Development/Movie_App/index.html
- Web Development/Movie_App/script.js
- Web Development/Movie_App/style.css
| Fixes       | #604 |
I want to add a Movie-Search App or webpage which is well-designed and provides adequate information about movies.
* We can search the movies in the search bar.
* We can hover on any movie to see the short description or overview of it.
* We can also see the ratings of movies.
> Adding a Movie App

- Web Development/Drink_Water_Goal/Readme.md
- Web Development/Drink_Water_Goal/index.html
- Web Development/Drink_Water_Goal/script.js
- Web Development/Drink_Water_Goal/style.css
| Fixes       | #605 |
This project helps a user to calculate the capacity how much water he can drink in a day in a Goal of 2 Litres.
This has been tested on my local browser.
> Adding Drink Water Goal App

- Web Development/Notes_App/Readme.md
- Web Development/Notes_App/index.html
- Web Development/Notes_App/script.js
- Web Development/Notes_App/style.css
| Fixes       | #612 |
A project that helps to write many important notes in one place.
This has been tested ion my local browser.
> Adding Notes App

- Web Development/Password_Generator/Readme.md
- Web Development/Password_Generator/index.html
- Web Development/Password_Generator/script.js
- Web Development/Password_Generator/style.css
| Fixes       | #615 |
A project which helps to generate Random strong or weak passwords depending on the user desire with great many inceptions and exceptions.
* We can generate upto maximum 20 lengths password.
* We can include or exclude uppercase and lowercase letters in our password.
* We can include or exclude numbers in our password.
* We can include or exclude special symbols in our password.
* We can use the Copy button provided to copy the password to our clipboard.
This has been tested on my local browser.
> Adding Project Password Generator

- JAVA/Employee Management/EmployeeManagement.java
- JAVA/Employee Management/readme.md
> Employeemanagement

- JAVA/InterestCalculator/Account.java
- JAVA/InterestCalculator/FDaccount.java
- JAVA/InterestCalculator/InterestCalculator.java
- JAVA/InterestCalculator/InvalidAgeException.java
- JAVA/InterestCalculator/InvalidAmountException.java
- JAVA/InterestCalculator/InvalidDaysException.java
- JAVA/InterestCalculator/InvalidMonthsException.java
- JAVA/InterestCalculator/RDaccount.java
- JAVA/InterestCalculator/SBaccount.java
- JAVA/InterestCalculator/readme.md
> Intrestcal

- Web Development/Cards_Expansion/Readme.md
- Web Development/Cards_Expansion/index.html
- Web Development/Cards_Expansion/script.js
- Web Development/Cards_Expansion/style.css
| Fixes       | #648 |
A project that is uniquely designed that helps to expand the image cards.
* This idea can be used in large projects to expand the different kinds of services.
> Adding Cards Expansion Project

- Web Development/Two_Buttons_Vertical_Slider/Readme.md
- Web Development/Two_Buttons_Vertical_Slider/index.html
- Web Development/Two_Buttons_Vertical_Slider/script.js
- Web Development/Two_Buttons_Vertical_Slider/style.css
| Fixes       | #647 |
A project which is to slide the page vertically with two sliding buttons.
* It has two buttons to slide vertically.
* This project idea can be used in large projects.
> Adding Vertical Slider Project

- Web Development/Double_Click_Like/Readme.md
- Web Development/Double_Click_Like/index.html
- Web Development/Double_Click_Like/script.js
- Web Development/Double_Click_Like/style.css
| Fixes       | #644 |
A project that adsd a Like or Heart by double-clicking on it.
* It shows the total number of likes that is given by double-click.
> Adding Double Click Like Project

- Python/word to pdf/.idea/.gitignore
- Python/word to pdf/.idea/inspectionProfiles/Project_Default.xml
- Python/word to pdf/.idea/inspectionProfiles/profiles_settings.xml
- Python/word to pdf/.idea/misc.xml
- Python/word to pdf/.idea/modules.xml
- Python/word to pdf/.idea/word to pdf.iml
- Python/word to pdf/README.md
- Python/word to pdf/main.py
> word to pdf

- .github/ISSUE_TEMPLATE/create-an-issue.yaml
> Issue Template Update
